spring:
  application:
    name: planets-service

  data:
    mongodb:
      host: sw-planets-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: sw-service
      port: 27017

server:
  context-path: /planets
  port: 80

---
spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: sw-service
      port: 27017